config/routes.rb
Rails.application.routes.draw do
  root 'static#index'
  resource :users
  resource :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user,  :class_name => 'User', :foreign_key => 'user_id'
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    def index

    end

    def new
      @profile = Profile.new
    end

    def show
      @profile = Profile.find(params[:id])
    end

    def create


    end


    def edit

    end

    def update

    end


end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def show
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(allowed_params)
    @user.save
    redirect_to users_path

  end

  def edit
  end

  private

  def allowed_params
    params.require(:user).permit(:name, :age, :description)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserProfiles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>Profiles index</h1>

app/views/profiles/new.html.erb
<%= form_for @profile do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= f.label :name %>
  <%= f.text_field :name %>
<%= f.label :age %>
  <%= f.number_field :age %>
<%= f.label :description %>
  <%= f.text_area :description %>
<%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>New user page </h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Hello from the show page</h1>

<table>
<tr>
  <th>Firstname</th>
  <th>Age</th>
  <th>Description</th>
</tr>
<tr>
  <% @users.each do |user| %>
  <td>  <%= user.name %></td>

  <td>  <%= user.age %></td>
  <td>  <%= user.description %></td>
</tr>
<% end %>
</table>
  <%= link_to " Create User", new_users_path %>